vscode:
  extensions:
    - EditorConfig.EditorConfig@0.13.0:80WlBivHWuQqyZAmK3HDxA==
    - dbaeumer.vscode-eslint@1.9.0:uGVJF/7Oqvahat42JFHY/Q==
    - svipas.prettier-plus@2.0.0:x19AdpDW9UOEZfkvBV8ijA==
    - jpoissonnier.vscode-styled-components@0.0.26:mtMkjJrLDD5C2eLocxpWzg==
    - shinnn.stylelint@0.51.0:Uy6xDb5psDPzfFra0dwP4w==
